version: "3.7"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - REDIS_URL=redis://redis
      - MONGO_URL=mongodb://mongo
    depends_on:
      - redis
      - mongo
  redis:
    image: redis/redis-stack:latest

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: